CREATE DATABASE SENAI_HROADS_MANHA

USE SENAI_HROADS_MANHA

CREATE TABLE Empresas
(
	IdEmpresa INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200) NOT NULL UNIQUE
	,CNPJ VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE Classes
(
	IdClasse INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE Habilidades
(
	IdHabilidade INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200) NOT NULL UNIQUE
	,IdTipoHabilidade INT FOREIGN KEY REFERENCES TiposHabilidades (IdTipoHabilidade) 
);

CREATE TABLE TiposJogos
(
	IdTipoJogo INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE Jogos
(
	IdJogo INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200) NOT NULL UNIQUE
	,IdTipoJogo INT FOREIGN KEY REFERENCES TiposJogos (IdTipoJogo) 
	,IdEmpresa INT FOREIGN KEY REFERENCES Empresas (IdEmpresa)
);

CREATE TABLE TiposHabilidades
(
	IdTipoHabilidade INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE ClassesHabilidades
(
	IdClasse INT FOREIGN KEY REFERENCES Classes (IdClasse)
	,IdHabilidade INT FOREIGN KEY REFERENCES Habilidades (IdHabilidade)
);

CREATE TABLE Personagens 
(
	IdPersonagem INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200) NOT NULL UNIQUE
	,IdClasse INT FOREIGN KEY REFERENCES Classes (IdClasse)
	,CapacidadeMaximaVida INT 
	,CapacidadeMaximaMana INT
	,DataAtualizacao DATE
	,DataCriacao DATE
	,IdJogo INT FOREIGN KEY REFERENCES Jogos(IdJogo)
);